ROOT_PATH = '/home/vm/demo'
SAMPLE_PATH = '/static/animals'
SAMPLE_URL ='/static/animals'
UPLOAD_PATH = '/static/upload'
CONTENT_TYPE_KEY = 'Content-Type'
CONTENT_TYPE = 'application/octet-stream'
SUBSCRIPTION_KEY = '<add API key here>' 
AUTHORIZATION_HEADER = 'Ocp-Apim-Subscription-Key'
BASE_URL = '<add api base url here>'
API_VERSION = '0.1'
SHOW_BBOX=False
MAX_FILE_SIZE = 3750000
